monitor=,preferred,auto,auto

env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct 
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1
env = MOZ_ENABLE_WAYLAND,1

exec-once = waybar & hyprpaper

# startup workspace
exec-once = [workspace 10;stayfocused;float;size 36% 72.6%;move 31 560] alacritty -e btop
exec-once = [workspace 10;float;size 36% 20%;move 31 88] alacritty -e vis
exec-once = workspace 10
